apiVersion: apps/v1
kind: Deployment
metadata:
  name: hopperv1
spec:
  selector:
    matchLabels:
      app: hopperv1
  replicas: 1
  template:
    metadata:
      labels:
        app: hopperv1
    spec:
      containers:
        - name: hopperv1
          image: phyominhtun/hopper-argocd:1fc5967a357dd01cb0df8bf25ecade8c795d5ede
          imagePullPolicy: Always
          ports:
            - containerPort: 80
