apiVersion: apps/v1
kind: Deployment
metadata:
  name: hopperv1
spec:
  selector:
    matchLabels:
      app: hopperv1
  replicas: 1
  template:
    metadata:
      labels:
        app: hopperv1
    spec:
      containers:
        - name: hopperv1
          image: phyominhtun/hopper-argocd:c42b20a21986a25889dcd0f42fe2162d16535650
          imagePullPolicy: Always
          ports:
            - containerPort: 80
