apiVersion: apps/v1
kind: Deployment
metadata:
  name: hopperv1
spec:
  selector:
    matchLabels:
      app: hopperv1
  replicas: 1
  template:
    metadata:
      labels:
        app: hopperv1
    spec:
      containers:
        - name: hopperv1
          image: phyominhtun/hopper-argocd:bf22c6506656d458d13844d9a047d915438f82e6
          imagePullPolicy: Always
          ports:
            - containerPort: 80
