apiVersion: apps/v1
kind: Deployment
metadata:
  name: hopperv1
  namespace: amd-app
spec:
  selector:
    matchLabels:
      app: hopperv1
  replicas: 1
  template:
    metadata:
      labels:
        app: hopperv1
    spec:
      containers:
      - name: hopperv1
        image: phyominhtun/hopper-circleci-argocd:cptmarvel-55
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      nodeSelector:
        pool: amd
      imagePullSecrets:
      - name: dockerhub-secret
