apiVersion: apps/v1
kind: Deployment
metadata:
  name: hopperv1
spec:
  selector:
    matchLabels:
      app: hopperv1
  replicas: 1
  template:
    metadata:
      labels:
        app: hopperv1
    spec:
      containers:
        - name: hopperv1
          image: phyominhtun/hopper-argocd:365eb5d9d0bb0657ebdb818e31aa33e6b6682215
          imagePullPolicy: Always
          ports:
            - containerPort: 80
