apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hopper-argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/josephphyo/argocd-app-configs.git
    targetRevision: HEAD
    path: hopper
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app-space
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

