apiVersion: apps/v1
kind: Deployment
metadata:
  name: hopperv2
spec:
  selector:
    matchLabels:
      app: hopperv2
  replicas: 1
  template:
    metadata:
      labels:
        app: hopperv2
    spec:
      containers:
      - name: hopperv2
        image: phyominhtun/hopper-argocd:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
