apiVersion: apps/v1
kind: Deployment
metadata:
  name: hopper
spec:
  selector:
    matchLabels:
      app: hopper
  replicas: 1
  template:
    metadata:
      labels:
        app: hopper
    spec:
      containers:
      - name: hopper
        image: phyominhtun/hopper-argocd:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
