apiVersion: apps/v1
kind: Deployment
metadata:
  name: hopper
spec:
  selector:
    matchLabels:
      app: hopper
  replicas: 1
  template:
    metadata:
      labels:
        app: hopper
    spec:
      containers:
      - name: hopper
        image: 359073224575.dkr.ecr.ap-southeast-1.amazonaws.com/hopper-is-back:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regcred

