name: Repository Dispatch

on:
  repository_dispatch:
    types: [argo-new-image-update]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update ArgoCD Deployment Image Version
      id: imgupd
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i hopper/hopper-v1/hopper-deploy-v1.yaml
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: github action apply argocd image name changes
